#
# Minimal docker-compose file for development.
#
# Bring up service using:
#   docker-compose up
#
version: "3.8"
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - DBA_PASSWORD=myDbaPassword
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.ndc.com/test-graph

  backend:
    image: gcr.io/distroless/java:11-debug-nonroot
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "sh", "/app/gradlew" ]
    command:
      - bootRun
    ports:
      - 8080:8080