#
# Minimal docker-compose file for development.
#
# Lint code using:
#   docker-compose up super-linter
#
version: "3.8"
services:
  # Basic development container.
  dev:
    # user: "${UID}:${GID}"
    image: gcr.io/distroless/java:11-debug-nonroot
    volumes:
    - .:/code
    entrypoint: ["tail", "-f", "/etc/hosts"]

  test:
    image: gcr.io/distroless/java:11-debug-nonroot
    volumes:
    - .:/code
    working_dir: /code
    entrypoint: ["sh", "/code/gradlew"]
    command:
    - clean
    - build
    - dependencyCheckAnalyze
    - spotbugsMain
    - spotbugsTest
