#
# Minimal docker-compose file for development.
#
# Bring up service using:
#   docker-compose up
#
version: "3.8"
services:
  virtuoso:
    image: tenforce/virtuoso
    ports:
      - 8890:8890
    environment:
      - SPARQL_UPDATE=true
      - DEFAULT_GRAPH=http://www.ndc.com/test-graph

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

  mysql:
    image: mysql
    command: --mysql-native-password=ON
    restart: no
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: dev_ndc_harvest

  backend:
    image: gcr.io/distroless/java:11-debug-nonroot
    restart: no
    depends_on:
      - virtuoso
      - mysql
      - elasticsearch
    volumes:
      - ${PWD}/build/libs/:/jar
    command: [ "/jar/dati-semantic-backend-0.0.1-SNAPSHOT.jar" ]
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      # Datasources
      - SPRING_ELASTICSEARCH_REST_URIS=http://elasticsearch:9200
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/dev_ndc_harvest
      - VIRTUOSO_SPARQL=http://virtuoso:8890/sparql
      - VIRTUOSO_SPARQL_GRAPH_STORE=http://virtuoso:8890/sparql-graph-crud
      - VIRTUOSO_USERNAME=dba
      - VIRTUOSO_PASSWORD=dba
      # Configuration.
      - HARVESTER_FOLDER_SKIP-WORDS=scriptR2RML,sparql,deprecated
      - HARVESTER_ONTOLOGY_SCANNER_SKIP-WORDS=example,aligns,DBGT,r2rml
      - HARVESTER_CONTROLLED-VOCABULARY_SCANNER_SKIP-WORDS=transparency-obligation-organization,transparency-obligation-administration
      # Repositories.
      - HARVESTER_REPOSITORIES=https://github.com/ronytw/sample-ontology-repo
      - HARVESTER_ENDPOINT_ENABLED=true
