create table HARVEST_ASSET_STATE
(
    ID               VARCHAR(256)  PRIMARY KEY,
    HARVESTER_RUN_ID VARCHAR(256)  NOT NULL REFERENCES HARVESTER_RUN (ID),
    REPO_URL         VARCHAR(2048) NOT NULL,
    AGENCY_ID        VARCHAR(256)  NOT NULL,
    KEY_CONCEPT      VARCHAR(256)  NOT NULL,
    SOURCE_DB_HASH   VARCHAR(64)   NOT NULL,
    DETECTED_AT      TIMESTAMP     NOT NULL,
    INDEX HARVEST_ASSET_STATE_RUN_ASSET_IDX (HARVESTER_RUN_ID, AGENCY_ID, KEY_CONCEPT)
) ENGINE = InnoDB;
