create table HARVEST_RESOURCE_DELTA
(
    ID               VARCHAR(256)  PRIMARY KEY,
    HARVESTER_RUN_ID VARCHAR(256)  NOT NULL REFERENCES HARVESTER_RUN (ID),
    ASSET_IRI        VARCHAR(2048) NOT NULL,
    ASSET_TYPE       VARCHAR(32)   NOT NULL,
    CHANGE_KIND      VARCHAR(16)   NOT NULL,
    SUMMARY_JSON     TEXT          NULL,
    CREATED_AT       TIMESTAMP     NOT NULL,
    UNIQUE KEY UQ_RUN_ASSET (HARVESTER_RUN_ID, ASSET_IRI(512)),
    INDEX IDX_RESOURCE_DELTA_ASSET (ASSET_IRI(512)),
    INDEX IDX_RESOURCE_DELTA_RUN   (HARVESTER_RUN_ID)
) ENGINE = InnoDB;
