create table SEMANTIC_CONTENT_STATS
(
    ID               VARCHAR(256) PRIMARY KEY,
    HARVESTER_RUN_ID VARCHAR(256) NOT NULL REFERENCES HARVESTER_RUN (ID),
    RESOURCE_URI     VARCHAR(255) NOT NULL,
    RESOURCE_TYPE    VARCHAR(64)  NOT NULL,
    RIGHT_HOLDER     VARCHAR(64)  NOT NULL,
    ISSUED_ON        TIMESTAMP    NOT NULL,
    MODIFIED_ON      TIMESTAMP    NOT NULL,
    HAS_ERRORS       BOOLEAN      NOT NULL,
    HAS_WARNINGS     BOOLEAN      NOT NULL,
    STATUS           TEXT         NOT NULL
) ENGINE = InnoDB;
