#
# This action checks that the OAS files inside the repository are valid according
#   to the Italian API guidelines.
#
#  TODO: check if spectral-action supports remote rulesets.
#  TODO: consider pinning the ruleset version.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write

jobs:
  spectral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl https://raw.githubusercontent.com/italia/api-oas-checker/ff44a035af8f9ebcdd605f3edb93c7b054c17a22/rulesets/spectral-full.yml > .spectral.yml

      # Get additional module required by spectral-full
      - run: mkdir functions
      - run: curl https://raw.githubusercontent.com/italia/api-oas-checker/f6f4e6e360b2ce9816dcca29396571dda1c6027d/security/functions/checkSecurity.js > functions/checkSecurity.js

      - uses: stoplightio/spectral-action@v0.8.8
        with:
          file_glob: 'src/main/resources/public/openapi.yaml'
